public class Scorer {
public static string[,] Scores = new string[,] {
{"Love-All","Love-Fifteen","Love-Thirty","Love-Forty","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2"},
{"Fifteen-Love","Fifteen-All","Fifteen-Thirty","Fifteen-Forty","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2"},
{"Thirty-Love","Thirty-Fifteen","Thirty-All","Thirty-Forty","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2"},
{"Forty-Love","Forty-Fifteen","Forty-Thirty","Deuce","Advantage player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2"},
{"Win for player1","Win for player1","Win for player1","Advantage player1","Deuce","Advantage player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2"},
{"Win for player1","Win for player1","Win for player1","Win for player1","Advantage player1","Deuce","Advantage player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2"},
{"Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Advantage player1","Deuce","Advantage player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2"},
{"Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Advantage player1","Deuce","Advantage player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2"},
{"Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Advantage player1","Deuce","Advantage player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2"},
{"Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Advantage player1","Deuce","Advantage player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2"},
{"Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Advantage player1","Deuce","Advantage player2","Win for player2","Win for player2","Win for player2","Win for player2","Win for player2"},
{"Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Advantage player1","Deuce","Advantage player2","Win for player2","Win for player2","Win for player2","Win for player2"},
{"Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Advantage player1","Deuce","Advantage player2","Win for player2","Win for player2","Win for player2"},
{"Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Advantage player1","Deuce","Advantage player2","Win for player2","Win for player2"},
{"Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Advantage player1","Deuce","Advantage player2","Win for player2"},
{"Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Advantage player1","Deuce","Advantage player2"},
{"Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Win for player1","Advantage player1","Deuce"}
};
}
